---
abstract: 'Test Anything interface for testing Exim4 configurations'
author:
  - 'Nigel Metheringham <nigelm@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-MTA-Exim4
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  IPC::Cmd: 0
  Test::Builder: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
